AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Deployment Wrapper from Cyclic:
  https://github.com/cyclic-software/app-aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  AppApiAccessLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7

  AppFunctionLog:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Sub '/aws/lambda/${AppLambda}'

  AppApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt AppApiAccessLog.Arn
        Format: $context.identity.sourceIp - - [$context.requestTime] "$context.httpMethod $context.routeKey $context.protocol" $context.status $context.responseLength $context.requestId $context.authorizer.error
      Auth:
        Authorizers:
          Auth0Identity:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              audience:
                - https://auth0-jwt-authorizer
              issuer: "https://cyclic.us.auth0.com/"
        DefaultAuthorizer: Auth0Identity

  AppLambda:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
    Properties:
      PackageType: Image
      Events: # Both / and /{path} are needed to properly capture all routes
        AppRoot:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: AppApi
            Path: /
            Method: any
        AppAny:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: AppApi
            Path: /{proxy+}
            Method: any

Outputs:
  # ServerlessHttpApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  AppApi:
    Description: "API Gateway endpoint URL for Prod stage for App function"
    Value: !Sub 'https://${AppApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/' # "https://${AppApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
  AppLambda:
    Description: "App Lambda ARN"
    Value: !GetAtt AppLambda.Arn
  AppLambdaIamRole:
    Description: "Implicit IAM Role created for App Lambda"
    Value: !GetAtt AppLambdaRole.Arn
  AppApiAccessLog:
    Description: "API Gateway access logs"
    Value: !GetAtt AppApiAccessLog.Arn
  AppFunctionLog:
    Description: "Lambda Logs for App"
    Value: !GetAtt AppFunctionLog.Arn
